// Device Info
#define CHIP_DEVICE_CONFIG_DEVICE_NAME "Staubsauger"
#define CHIP_DEVICE_CONFIG_PRODUCT_NAME "x500"
#define CHIP_DEVICE_CONFIG_MANUFACTURER_NAME "Tesvor"
#define CHIP_DEVICE_CONFIG_DEVICE_TYPE 0x0074

// Software Version
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING "0.1"

// DISCRIMINATOR, PIN & SPAKE2P_SALT
/*
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_DISCRIMINATOR 0xF00
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE 20202021
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_SALT "U1BBS0UyUCBLZXkgU2FsdA=="
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_VERIFIER "uWFwqugDNGiEck/po7KHwwMwwqZgN10XuyBajPGuyzUEV/iree4lOrao5GuwnlQ65CJzbeUB49s31EH+NEkg0JVI5MGCQGMMT/SRPFNRODm3wH/MBiehuFc6FJ/NH6Rmzw=="
*/

// Test Vendor and Product ID
#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_ID 0xFFF1
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_ID 0x8002